version: '3'

services:
  web:
    image: nginx
    container_name: web-test
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=http"
      - "traefik.http.routers.nginx.rule=Host(`local.yourdomain.com`)" # if you want a internal domain, get the wildcard cert for it and then choos traefik-dashboard.home.local.yourdomain.com or what you want
      - "traefik.http.middlewares.nginx-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nginx.middlewares=nginx-https-redirect"
      - "traefik.http.routers.nginx-secure.entrypoints=https"
      - "traefik.http.routers.nginx-secure.rule=Host(`local.yourdomain.com`)"
      - "traefik.http.routers.nginx-secure.tls=true"
      - 'traefik.http.routers.nginx-secure.service=nginx'
      - 'traefik.http.services.nginx.loadbalancer.server.port=80'
      - 'traefik.docker.network=proxy'

networks:
  proxy:
    external: true